apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hytale-data
  namespace: hytale
  labels:
    app: hytale-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
