apiVersion: v1
kind: Service
metadata:
  name: hytale-server
  namespace: hytale
  labels:
    app: hytale-server
spec:
  type: NodePort
  selector:
    app: hytale-server
  ports:
    - port: 5520
      targetPort: 5520
      nodePort: 30520
      protocol: UDP
      name: game
